# Vertical Candidate List
Vertical Candidate List=False
# Wheel For Paging
WheelForPaging=True
# Font
Font="@font@ 13"
# Menu Font
MenuFont="@font@ 13"
# Tray Font
TrayFont="@font@ 12"
# Theme
Theme=@theme@
# Dark Theme
DarkTheme=@theme@
# Use Dark Theme
UseDarkTheme=False
# Use Per Screen DPI
PerScreenDPI=True
