[Metadata]
Name=Monet
Version=1
Author=Home Manager
Description=Material Design 3 dynamic color theme
ScaleWithDPI=True

[InputPanel]
Font=@font@ 13
NormalColor=@on_surface@
HighlightCandidateColor=@on_primary@
HighlightColor=@on_surface_variant@
HighlightBackgroundColor=@surface_container@
Spacing=4
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=12
Right=12
Top=8
Bottom=8

[InputPanel/ContentMargin]
Left=4
Right=4
Top=4
Bottom=4

[InputPanel/Background]
Color=@surface_container@
BorderColor=@outline_variant@
BorderWidth=1

[InputPanel/Background/Margin]
Left=3
Right=3
Top=3
Bottom=3

[InputPanel/Highlight]
Color=@primary@

[InputPanel/Highlight/Margin]
Left=12
Right=12
Top=8
Bottom=8

[Menu/Background]
Color=@surface_container@
BorderColor=@outline_variant@
BorderWidth=1

[Menu/Background/Margin]
Left=3
Right=3
Top=3
Bottom=3

[Menu/ContentMargin]
Left=4
Right=4
Top=4
Bottom=4

[Menu/Highlight]
Color=@primary_container@

[Menu/Highlight/Margin]
Left=12
Right=12
Top=8
Bottom=8

[Menu/Separator]
Color=@outline_variant@

[Menu/CheckBox]
Image=radio.png

[Menu/SubMenu]
Image=arrow.png

[Menu/TextMargin]
Left=8
Right=8
Top=7
Bottom=7

[AccentColorField]
0=Input Panel Border
1=Input Panel Highlight Candidate Background
2=Input Panel Highlight
3=Menu Border
4=Menu Separator
5=Menu Selected Item Background
