[Metadata]
Name=Monet
Version=1
Author=Home Manager
Description=Material Design 3 dynamic color theme
ScaleWithDPI=True

[InputPanel]
Font=@font@ 13
NormalColor=@on_surface@
HighlightCandidateColor=@on_primary_container@
HighlightColor=@on_surface_variant@
HighlightBackgroundColor=@surface_container_highest@
Spacing=8
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=14
Right=14
Top=9
Bottom=9

[InputPanel/ContentMargin]
Left=8
Right=8
Top=8
Bottom=8

[InputPanel/Background]
Color=@surface_container_high@
BorderColor=@outline_variant@
BorderWidth=1

[InputPanel/Background/Margin]
Left=8
Right=8
Top=8
Bottom=8

[InputPanel/Highlight]
Color=@primary_container@

[InputPanel/Highlight/Margin]
Left=14
Right=14
Top=9
Bottom=9

[Menu]
NormalColor=@on_surface@
HighlightCandidateColor=@on_secondary_container@
HighlightColor=@on_secondary_container@

[Menu/Background]
Color=@surface_container_high@
BorderColor=@outline_variant@
BorderWidth=1

[Menu/Background/Margin]
Left=8
Right=8
Top=8
Bottom=8

[Menu/ContentMargin]
Left=8
Right=8
Top=8
Bottom=8

[Menu/Highlight]
Color=@secondary_container@

[Menu/Highlight/Margin]
Left=14
Right=14
Top=9
Bottom=9

[Menu/Separator]
Color=@outline@

[Menu/CheckBox]
Image=radio.png

[Menu/SubMenu]
Image=arrow.png

[Menu/TextMargin]
Left=12
Right=12
Top=8
Bottom=8

[AccentColorField]
0=Input Panel Border
1=Input Panel Highlight Candidate Background
2=Input Panel Highlight
3=Menu Border
4=Menu Separator
5=Menu Selected Item Background
