general {
  no_fade_in = false
  no_fade_out = false
  hide_cursor = true
  grace = 0
  disable_loading_bar = true
  ignore_empty_input = true
}

input-field {
  monitor =
  size = 320, 64
  outline_thickness = 2
  dots_size = 0.22
  dots_spacing = 0.35
  dots_center = true
  fade_on_empty = false
  rounding = 24
  outer_color = rgb(@outline_variant_rgb@)
  inner_color = rgb(@surface_container_high_rgb@)
  font_color = rgb(@on_surface_rgb@)
  check_color = rgb(@primary_rgb@)
  fail_color = rgb(@error_rgb@)
  placeholder_text = <span foreground="##@on_surface_variant_rgb@">Password</span>
  hide_input = false
  position = 0, -200
  halign = center
  valign = center
  fail_text = <span foreground="##@error_rgb@"><b>$ATTEMPTS</b></span>
  fail_timeout = 2000
  fail_transition = 300
}

label {
  monitor =
  text = cmd[update:1000] date +"%A, %B %d"
  color = rgb(@on_surface_variant_rgb@)
  font_size = 22
  font_family = @font_family@
  position = 0, 300
  halign = center
  valign = center
}

label {
  monitor =
  text = cmd[update:1000] date +"%-I:%M"
  color = rgb(@on_surface_rgb@)
  font_size = 95
  font_family = @font_family@
  position = 0, 200
  halign = center
  valign = center
}
