{ config, lib }:

let
  enabled = config.homeModules.terminal.btop.enable;
  homeDir = config.home.homeDirectory;
  currentSymlink = "${homeDir}/.local/share/themes/current";
in
{
  enable = enabled;
  outputDirs = [ "$out/btop/themes" ];

  generate =
    { polarity }:
    ''
      jq -r '
        def c($name): .colors[$name]["${polarity}"].color;
        [
          "# Generated by matugen using Material Design 3 color roles",
          "theme[main_bg]=\"" + c("surface_container_lowest") + "\"",
          "theme[main_fg]=\"" + c("on_surface") + "\"",
          "theme[title]=\"" + c("primary") + "\"",
          "theme[hi_fg]=\"" + c("primary") + "\"",
          "theme[selected_bg]=\"" + c("primary_container") + "\"",
          "theme[selected_fg]=\"" + c("on_primary_container") + "\"",
          "theme[inactive_fg]=\"" + c("on_surface_variant") + "\"",
          "theme[graph_text]=\"" + c("on_surface_variant") + "\"",
          "theme[meter_bg]=\"" + c("surface_container_highest") + "\"",
          "theme[proc_misc]=\"" + c("tertiary") + "\"",
          "theme[cpu_box]=\"" + c("outline_variant") + "\"",
          "theme[mem_box]=\"" + c("outline_variant") + "\"",
          "theme[net_box]=\"" + c("outline_variant") + "\"",
          "theme[proc_box]=\"" + c("outline_variant") + "\"",
          "theme[div_line]=\"" + c("outline_variant") + "\"",
          "theme[temp_start]=\"" + c("primary") + "\"",
          "theme[temp_mid]=\"" + c("tertiary") + "\"",
          "theme[temp_end]=\"" + c("error") + "\"",
          "theme[cpu_start]=\"" + c("primary") + "\"",
          "theme[cpu_mid]=\"" + c("primary_container") + "\"",
          "theme[cpu_end]=\"" + c("tertiary") + "\"",
          "theme[free_start]=\"" + c("secondary_container") + "\"",
          "theme[free_mid]=\"" + c("secondary") + "\"",
          "theme[free_end]=\"" + c("primary") + "\"",
          "theme[cached_start]=\"" + c("surface_container_high") + "\"",
          "theme[cached_mid]=\"" + c("secondary") + "\"",
          "theme[cached_end]=\"" + c("tertiary") + "\"",
          "theme[available_start]=\"" + c("tertiary_container") + "\"",
          "theme[available_mid]=\"" + c("primary") + "\"",
          "theme[available_end]=\"" + c("secondary") + "\"",
          "theme[used_start]=\"" + c("primary") + "\"",
          "theme[used_mid]=\"" + c("secondary") + "\"",
          "theme[used_end]=\"" + c("error") + "\"",
          "theme[download_start]=\"" + c("tertiary_container") + "\"",
          "theme[download_mid]=\"" + c("secondary") + "\"",
          "theme[download_end]=\"" + c("primary") + "\"",
          "theme[upload_start]=\"" + c("primary_container") + "\"",
          "theme[upload_mid]=\"" + c("secondary") + "\"",
          "theme[upload_end]=\"" + c("tertiary") + "\"",
          "theme[process_start]=\"" + c("secondary_container") + "\"",
          "theme[process_mid]=\"" + c("secondary") + "\"",
          "theme[process_end]=\"" + c("tertiary") + "\""
        ] | .[]
      ' colors.json > "$out/btop/themes/monet.theme"
    '';

  activation.linkBtopTheme = lib.hm.dag.entryAfter [ "initThemeLinks" "cleanupDarkmanLegacyHooks" ] ''
    BTOP_THEME="${homeDir}/.config/btop/themes/monet.theme"
    THEME_BTOP="${currentSymlink}/btop/themes/monet.theme"

    if [ -f "$THEME_BTOP" ]; then
      $DRY_RUN_CMD mkdir -p "$(dirname "$BTOP_THEME")"
      $DRY_RUN_CMD rm -f "$BTOP_THEME"
      $DRY_RUN_CMD ln -sfn "$THEME_BTOP" "$BTOP_THEME"
    fi
  '';
}
