{ config, themeLib }:

let
  enabled = config.programs.ghostty.enable;
in
themeLib.mkApp {
  enable = enabled;
  outputDirs = [ "$out/ghostty/themes" ];

  generate =
    { polarity }:
    ''
      jq -r '
        def c($name): .colors[$name]["${polarity}"].color;
        [
          "# Generated by matugen using Material Design 3 color roles",
          "background = " + c("surface_container_lowest"),
          "foreground = " + c("on_surface"),
          "cursor-color = " + c("primary"),
          "cursor-text = " + c("on_primary"),
          "selection-background = " + c("primary_container"),
          "selection-foreground = " + c("on_primary_container"),
          "search-background = " + c("tertiary_container"),
          "search-foreground = " + c("on_tertiary_container"),
          "search-selected-background = " + c("primary_container"),
          "search-selected-foreground = " + c("on_primary_container"),
          "split-divider-color = " + c("outline_variant"),
          "unfocused-split-fill = " + c("surface_container"),
          "palette = 0=" + c("surface_container_high"),
          "palette = 1=" + c("error"),
          "palette = 2=" + c("tertiary"),
          "palette = 3=" + c("primary"),
          "palette = 4=" + c("secondary"),
          "palette = 5=" + c("primary"),
          "palette = 6=" + c("tertiary"),
          "palette = 7=" + c("on_surface"),
          "palette = 8=" + c("outline_variant"),
          "palette = 9=" + c("error"),
          "palette = 10=" + c("tertiary"),
          "palette = 11=" + c("primary"),
          "palette = 12=" + c("secondary"),
          "palette = 13=" + c("primary"),
          "palette = 14=" + c("tertiary"),
          "palette = 15=" + c("inverse_surface")
        ] | .[]
      ' colors.json > "$out/ghostty/themes/monet"
    '';

  links = [
    {
      name = "Ghostty";
      target = ".config/ghostty/themes/monet";
      source = "ghostty/themes/monet";
    }
  ];
}
