{ config, lib }:

let
  enabled = config.programs.gitui.enable;
  homeDir = config.home.homeDirectory;
  currentSymlink = "${homeDir}/.local/share/themes/current";
in
{
  enable = enabled;
  outputDirs = [ "$out/gitui" ];

  generate =
    { polarity }:
    ''
      jq -r '
        def c($name): .colors[$name]["${polarity}"].color;
        [
          "// Generated by matugen using Material Design 3 color roles",
          "(",
          "    selected_tab: Some(\"" + c("primary") + "\"),",
          "    command_fg: Some(\"" + c("on_primary_container") + "\"),",
          "    selection_bg: Some(\"" + c("primary_container") + "\"),",
          "    selection_fg: Some(\"" + c("on_primary_container") + "\"),",
          "    use_selection_fg: Some(true),",
          "    cmdbar_bg: Some(\"" + c("surface_container_high") + "\"),",
          "    disabled_fg: Some(\"" + c("on_surface_variant") + "\"),",
          "    diff_line_add: Some(\"" + c("secondary_container") + "\"),",
          "    diff_line_delete: Some(\"" + c("error_container") + "\"),",
          "    diff_file_added: Some(\"" + c("secondary") + "\"),",
          "    diff_file_removed: Some(\"" + c("error") + "\"),",
          "    diff_file_moved: Some(\"" + c("tertiary") + "\"),",
          "    diff_file_modified: Some(\"" + c("primary") + "\"),",
          "    commit_hash: Some(\"" + c("tertiary") + "\"),",
          "    commit_time: Some(\"" + c("on_surface_variant") + "\"),",
          "    commit_author: Some(\"" + c("secondary") + "\"),",
          "    danger_fg: Some(\"" + c("error") + "\"),",
          "    push_gauge_bg: Some(\"" + c("primary_container") + "\"),",
          "    push_gauge_fg: Some(\"" + c("on_primary_container") + "\"),",
          "    tag_fg: Some(\"" + c("tertiary") + "\"),",
          "    branch_fg: Some(\"" + c("primary") + "\"),",
          "    block_title_focused: Some(\"" + c("primary") + "\"),",
          ")"
        ] | .[]
      ' colors.json > "$out/gitui/theme.ron"
    '';

  xdgConfig."gitui/theme.ron" = {
    force = lib.mkForce true;
    text = "// Managed by Monet theme activation\n";
  };

  activation.linkGituiTheme =
    lib.hm.dag.entryAfter [ "initThemeLinks" "cleanupDarkmanLegacyHooks" ]
      ''
        GITUI_THEME="${homeDir}/.config/gitui/theme.ron"
        THEME_GITUI="${currentSymlink}/gitui/theme.ron"

        if [ -f "$THEME_GITUI" ]; then
          $DRY_RUN_CMD mkdir -p "$(dirname "$GITUI_THEME")"
          $DRY_RUN_CMD rm -f "$GITUI_THEME"
          $DRY_RUN_CMD ln -sfn "$THEME_GITUI" "$GITUI_THEME"
        fi
      '';
}
