{ config, lib }:

let
  enabled = config.programs.helix.enable;
  homeDir = config.home.homeDirectory;
  currentSymlink = "${homeDir}/.local/share/themes/current";
in
{
  enable = enabled;
  outputDirs = [ "$out/helix/themes" ];

  generate =
    { polarity }:
    ''
      jq -r '
        def c($name): .colors[$name]["${polarity}"].color;
        [
          "# Generated by matugen using Material Design 3 color roles",
          "",
          "\"ui.background\" = { fg = \"on_surface\", bg = \"surface\" }",
          "\"ui.background.separator\" = { fg = \"outline_variant\" }",
          "\"ui.text\" = \"on_surface\"",
          "\"ui.text.focus\" = \"on_surface\"",
          "\"ui.text.inactive\" = \"on_surface_variant\"",
          "\"ui.text.directory\" = \"primary\"",
          "\"ui.virtual\" = \"outline\"",
          "\"ui.virtual.whitespace\" = \"outline_variant\"",
          "\"ui.virtual.ruler\" = { bg = \"surface_container_low\" }",
          "\"ui.virtual.jump-label\" = { fg = \"tertiary\", modifiers = [\"bold\"] }",
          "\"ui.linenr\" = { fg = \"outline\", bg = \"surface_container_lowest\" }",
          "\"ui.linenr.selected\" = { fg = \"primary\", bg = \"surface_container_low\", modifiers = [\"bold\"] }",
          "\"ui.gutter\" = { bg = \"surface_container_lowest\" }",
          "\"ui.selection\" = { bg = \"primary_container\" }",
          "\"ui.selection.primary\" = { bg = \"secondary_container\" }",
          "\"ui.cursor\" = { fg = \"surface\", bg = \"primary\" }",
          "\"ui.cursor.primary\" = { fg = \"surface\", bg = \"primary\" }",
          "\"ui.cursor.insert\" = { fg = \"surface\", bg = \"secondary\" }",
          "\"ui.cursor.select\" = { fg = \"surface\", bg = \"tertiary\" }",
          "\"ui.cursor.match\" = { fg = \"tertiary\", modifiers = [\"underlined\"] }",
          "\"ui.cursorline.primary\" = { bg = \"surface_container_low\" }",
          "\"ui.statusline\" = { fg = \"on_surface_variant\", bg = \"surface_container\" }",
          "\"ui.statusline.inactive\" = { fg = \"outline\", bg = \"surface_container_low\" }",
          "\"ui.statusline.normal\" = { fg = \"on_primary\", bg = \"primary\" }",
          "\"ui.statusline.insert\" = { fg = \"on_secondary\", bg = \"secondary\" }",
          "\"ui.statusline.select\" = { fg = \"on_tertiary\", bg = \"tertiary\" }",
          "\"ui.popup\" = { fg = \"on_surface\", bg = \"surface_container_high\" }",
          "\"ui.popup.info\" = { fg = \"on_surface\", bg = \"surface_container_high\" }",
          "\"ui.window\" = { fg = \"outline_variant\" }",
          "\"ui.help\" = { fg = \"on_surface\", bg = \"surface_container_high\" }",
          "\"ui.menu\" = { fg = \"on_surface\", bg = \"surface_container_high\" }",
          "\"ui.menu.selected\" = { fg = \"on_primary_container\", bg = \"primary_container\" }",
          "\"ui.menu.scroll\" = { fg = \"outline\", bg = \"surface_container_high\" }",
          "\"ui.bufferline\" = { fg = \"on_surface_variant\", bg = \"surface_container_low\" }",
          "\"ui.bufferline.active\" = { fg = \"on_primary_container\", bg = \"primary_container\" }",
          "",
          "\"comment\" = { fg = \"outline\", modifiers = [\"italic\"] }",
          "\"attribute\" = \"tertiary\"",
          "\"type\" = \"secondary\"",
          "\"constructor\" = \"secondary\"",
          "\"constant\" = \"tertiary\"",
          "\"constant.numeric\" = \"tertiary\"",
          "\"constant.character.escape\" = \"primary\"",
          "\"string\" = \"secondary\"",
          "\"string.regexp\" = \"primary\"",
          "\"string.special\" = \"tertiary\"",
          "\"variable\" = \"on_surface\"",
          "\"variable.parameter\" = \"tertiary\"",
          "\"variable.builtin\" = \"primary\"",
          "\"variable.other.member\" = \"secondary\"",
          "\"label\" = \"tertiary\"",
          "\"punctuation\" = \"on_surface_variant\"",
          "\"punctuation.special\" = \"primary\"",
          "\"keyword\" = { fg = \"primary\", modifiers = [\"bold\"] }",
          "\"keyword.operator\" = \"tertiary\"",
          "\"operator\" = \"tertiary\"",
          "\"function\" = \"primary\"",
          "\"function.builtin\" = \"primary\"",
          "\"function.macro\" = { fg = \"primary\", modifiers = [\"bold\"] }",
          "\"tag\" = \"secondary\"",
          "\"namespace\" = \"tertiary\"",
          "\"special\" = \"primary\"",
          "",
          "\"markup.heading\" = { fg = \"primary\", modifiers = [\"bold\"] }",
          "\"markup.list\" = \"tertiary\"",
          "\"markup.bold\" = { fg = \"on_surface\", modifiers = [\"bold\"] }",
          "\"markup.italic\" = { fg = \"on_surface\", modifiers = [\"italic\"] }",
          "\"markup.strikethrough\" = { modifiers = [\"crossed_out\"] }",
          "\"markup.link.url\" = { fg = \"primary\", modifiers = [\"underlined\"] }",
          "\"markup.link.text\" = \"secondary\"",
          "\"markup.quote\" = { fg = \"on_surface_variant\", modifiers = [\"italic\"] }",
          "\"markup.raw\" = \"secondary\"",
          "",
          "\"diff.plus\" = \"secondary\"",
          "\"diff.delta\" = \"tertiary\"",
          "\"diff.minus\" = \"error\"",
          "\"info\" = \"primary\"",
          "\"hint\" = \"secondary\"",
          "\"warning\" = \"tertiary\"",
          "\"error\" = \"error\"",
          "\"diagnostic.hint\" = { underline = { color = \"secondary\", style = \"curl\" } }",
          "\"diagnostic.info\" = { underline = { color = \"primary\", style = \"curl\" } }",
          "\"diagnostic.warning\" = { underline = { color = \"tertiary\", style = \"curl\" } }",
          "\"diagnostic.error\" = { underline = { color = \"error\", style = \"curl\" } }",
          "\"diagnostic.unnecessary\" = { modifiers = [\"dim\"] }",
          "\"diagnostic.deprecated\" = { modifiers = [\"crossed_out\"] }",
          "",
          "[palette]",
          "surface = \"" + c("surface") + "\"",
          "surface_container_lowest = \"" + c("surface_container_lowest") + "\"",
          "surface_container_low = \"" + c("surface_container_low") + "\"",
          "surface_container = \"" + c("surface_container") + "\"",
          "surface_container_high = \"" + c("surface_container_high") + "\"",
          "on_surface = \"" + c("on_surface") + "\"",
          "on_surface_variant = \"" + c("on_surface_variant") + "\"",
          "outline = \"" + c("outline") + "\"",
          "outline_variant = \"" + c("outline_variant") + "\"",
          "primary = \"" + c("primary") + "\"",
          "on_primary = \"" + c("on_primary") + "\"",
          "primary_container = \"" + c("primary_container") + "\"",
          "on_primary_container = \"" + c("on_primary_container") + "\"",
          "secondary = \"" + c("secondary") + "\"",
          "on_secondary = \"" + c("on_secondary") + "\"",
          "secondary_container = \"" + c("secondary_container") + "\"",
          "tertiary = \"" + c("tertiary") + "\"",
          "on_tertiary = \"" + c("on_tertiary") + "\"",
          "error = \"" + c("error") + "\""
        ] | .[]
      ' colors.json > "$out/helix/themes/monet.toml"
    '';

  activation.linkHelixTheme =
    lib.hm.dag.entryAfter [ "initThemeLinks" "cleanupDarkmanLegacyHooks" ]
      ''
        HELIX_THEME="${homeDir}/.config/helix/themes/monet.toml"
        THEME_HELIX="${currentSymlink}/helix/themes/monet.toml"

        if [ -f "$THEME_HELIX" ]; then
          $DRY_RUN_CMD mkdir -p "$(dirname "$HELIX_THEME")"
          $DRY_RUN_CMD rm -f "$HELIX_THEME"
          $DRY_RUN_CMD ln -sfn "$THEME_HELIX" "$HELIX_THEME"
        fi
      '';
}
