{ config, lib }:

let
  enabled = config.programs.mpv.enable;
  homeDir = config.home.homeDirectory;
  currentSymlink = "${homeDir}/.local/share/themes/current";
in
{
  enable = enabled;
  outputDirs = [ "$out/mpv" ];

  generate =
    { polarity }:
    ''
      jq -r '
        def c($name): .colors[$name]["${polarity}"].color;
        def argb($alpha; $name): "\"#" + $alpha + (c($name) | ltrimstr("#")) + "\"";
        [
          "# Generated by matugen using Material Design 3 color roles",
          "background=color",
          "background-color=" + argb("FF"; "surface"),
          "",
          "osd-color=" + argb("FF"; "on_surface"),
          "osd-back-color=" + argb("E6"; "surface_container_high"),
          "osd-outline-color=" + argb("FF"; "outline_variant"),
          "osd-selected-color=" + argb("FF"; "primary"),
          "osd-selected-outline-color=" + argb("FF"; "primary_container"),
          "osd-border-style=background-box",
          "osd-outline-size=1",
          "osd-shadow-offset=0",
          "osd-bar-outline-size=0",
          "",
          "sub-color=" + argb("FF"; "inverse_on_surface"),
          "sub-back-color=" + argb("99"; "inverse_surface"),
          "sub-outline-color=" + argb("FF"; "inverse_surface"),
          "sub-border-style=outline-and-shadow",
          "sub-outline-size=2"
        ] | .[]
      ' colors.json > "$out/mpv/monet.conf"
    '';

  activation.linkMpvTheme = lib.hm.dag.entryAfter [ "initThemeLinks" "cleanupDarkmanLegacyHooks" ] ''
    MPV_THEME="${homeDir}/.config/mpv/monet.conf"
    THEME_MPV="${currentSymlink}/mpv/monet.conf"

    if [ -f "$THEME_MPV" ]; then
      $DRY_RUN_CMD mkdir -p "$(dirname "$MPV_THEME")"
      $DRY_RUN_CMD rm -f "$MPV_THEME"
      $DRY_RUN_CMD ln -sfn "$THEME_MPV" "$MPV_THEME"
    fi
  '';
}
